version: '3.9'
services:
  app:
    build: .
    image: app
    expose:
       - "80"
#    ports:
#      - "80:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    links:
      - db
    networks:
      - afif-net
    deploy:
#      labels:
#        - traefik.http.routers.app.rule=Host('127.0.0.1')
#        - traefik.http.services.app.loadbalancer.server.port=80
      placement:
          constraints:
              - node.role == manager

  db:
    image: mysql:8.0
    expose:
       - "3306"
#    ports:
#      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: demo
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d
#      - mysql-data:/var/lib/mysql
    networks:
      - afif-net
    deploy:
      placement:
        constraints:
            - node.role == worker

volumes:
    mysql-data:
networks:
    afif-net:
      driver: overlay
      attachable: true
